#!/bin/bash

if [[ "$*" == "" ]]; then

	echo

	read -r -p "Enter domain name: " fqdn

	if ! [ -f /etc/nginx/sites-available/"$fqdn" ]; then

		echo -e "\n Site does \033[1;91m[NOT]\033[0m exist"
		echo
		exit 1;
	fi

	if [ -f /etc/nginx/sites-enabled/"$fqdn" ]; then

		echo -e "\n Site is already enabled! \033[33m[EXITING]\033[0m"
		echo
		exit 1;
	fi

	ln -s /etc/nginx/sites-available/"$fqdn" /etc/nginx/sites-enabled/"$fqdn"

	echo -e "\n Site \033[36m$fqdn\033[0m has been \033[32m[ENABLED]\033[0m"

	else

		for fqdn in "$@"; do

			if ! [ -f /etc/nginx/sites-available/"$fqdn" ]; then

				echo -e "\n Site does \033[1;91m[NOT]\033[0m exist"
				echo
				exit 1;
			fi

			if [ -f /etc/nginx/sites-enabled/"$fqdn" ]; then

				echo -e "\n Site is already enabled! \033[33m[EXITING]\033[0m"
				echo
				exit 1;
			fi

			ln -s /etc/nginx/sites-available/"$fqdn" /etc/nginx/sites-enabled/"$fqdn"

			echo -e "\n Site \033[36m$fqdn\033[0m has been \033[32m[ENABLED]\033[0m"

		done
	fi

lampstart