#!/bin/bash
#
# clk-nixinit :: haproxy
# HAProxy as an SNI router on 443. Local domains go to the nginx backend on
# 9443 over proxy_protocol, everything else to a per-domain remote backend.
#
# usage: make-haproxy.sh

##
# Variables
##

set -a											# export all variables

scriptdir=$(dirname "$(realpath "$0")")							# set script directory

# shellcheck source=../../lib/common.sh
. "$scriptdir"/../../lib/common.sh


##
# Configuration
##

need_root
logstart "haproxy"


##
# Script
##

banner "HAProxy"
cursoff

step "Updating repositories"
makespin "apt-get update"

step "Installing HAProxy"
makespin "apt_install haproxy"

step "Installing HAProxy customization"

# Backup default config
[[ -f /etc/haproxy/haproxy.cfg.bak ]] || mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Copy custom config
cp -f "$scriptdir"/confs/haproxy.cfg /etc/haproxy/haproxy.cfg

# Create log directory
mkdir -p /var/log/haproxy

# Modify HAProxy rsyslog.d log file location and template
if ! grep -q 'name="HAProxy"' /etc/rsyslog.d/49-haproxy.conf; then			# only ever prepend once
	sed -i '1i\# LogFormat\ntemplate(name="HAProxy" type="list") {\n    property(name="msg" spifno1stsp="on" )\n    property(name="msg" droplastlf="on" )\n    constant(value="\\n")\n    }\n' /etc/rsyslog.d/49-haproxy.conf
	sed -i 's|/var/log/haproxy.log|/var/log/haproxy/haproxy.log;HAProxy|' /etc/rsyslog.d/49-haproxy.conf
fi

systemctl restart rsyslog >>"$clklog" 2>&1

# Touch the SNI mapfiles entld.hpx writes into
[[ -f /etc/haproxy/localdomains.file ]] || printf '#SNI\n\n' > /etc/haproxy/localdomains.file
[[ -f /etc/haproxy/remotedomains.map ]] || printf '#SNI\t\tRemote Server\n\n' > /etc/haproxy/remotedomains.map

# Generated backends live one-per-file in conf.d, never in haproxy.cfg itself,
# so entld.hpx never has to edit the shipped config and distld.proxy can drop a
# backend by deleting a file. HAProxy has no include directive, but -f takes a
# directory and loads every .cfg in it, sorted -- so the unit gets a second -f
# through EXTRAOPTS. Parse order does not matter: backends are resolved after
# the whole config is read, so a frontend may reference one defined later.
mkdir -p /etc/haproxy/conf.d

# a comment-only file, so the directory is never empty and -f always has
# something valid to read
[[ -f /etc/haproxy/conf.d/00-generated.cfg ]] ||
	printf '# Backends generated by entld.hpx land in this directory, one file each.\n# Do not add anything by hand here that distld.proxy might delete.\n' \
		> /etc/haproxy/conf.d/00-generated.cfg

if ! grep -q 'conf\.d' /etc/default/haproxy 2>/dev/null; then				# only ever append once
	echo 'EXTRAOPTS="-f /etc/haproxy/conf.d"' >> /etc/default/haproxy
fi

# Modify HAProxy logrotate.d logs location
sed -i 's|/var/log/haproxy.log|/var/log/haproxy/*.log|' /etc/logrotate.d/haproxy
okay

# Install entld.hpx
step "Installing entld.hpx"
install -m 0755 "$scriptdir"/scripts/entld.hpx /usr/sbin/entld.hpx
okay

# Ignore the HAProxy runtime process in lfd
step "Adding HAProxy to the lfd exclusions"
if [[ -f /etc/csf/csf.pignore ]] && ! grep -q "exe:/usr/sbin/haproxy" /etc/csf/csf.pignore; then
	echo "exe:/usr/sbin/haproxy" >> /etc/csf/csf.pignore
	systemctl restart csf lfd >>"$clklog" 2>&1
	okay
else
	skip
fi

step "Testing the HAProxy configuration"
haproxy -c -f /etc/haproxy/haproxy.cfg -f /etc/haproxy/conf.d >>"$clklog" 2>&1 || fail	# same file set systemd loads
okay

step "Restarting HAProxy"
makespin "systemctl restart haproxy"

profile_set haproxy 1

curson

echo -e "${bgrn}   HAProxy complete!${cln}\n"
