###############################
### Clickwork Wildcard Tools ##
###############################

	Alias /php.info /var/www/wildcard/info.php
	Alias /php.cache /var/www/wildcard/cache.php
	Alias /php.CA /var/www/wildcard/phpCacheAdmin/

	<Directory /var/www/wildcard>
	  Require ip $hqips
	</Directory>
